MyInternetStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('myhome.urls')),
    path('blog/', include('blog.urls')),
    path('bags/', include('bags.urls')),
    path('covid19', include('covid19.urls')),
    path('accounts/', include('allauth.urls')),
    path('contact', include('contact.urls')),
    path('children/', include('children.urls')),
    path('yobit', include('yobit.urls')),
    path('finance_ua', include('finance.urls')),
    path('men/', include('men.urls')),

    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

men/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.men_main_view, name="men_main_view"),
    path('<int:id>', views.men_detail_view, name="men_detail_view"),

]

myhome/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('responds', views.responds, name="responds"),
    path('quickview', views.quickview, name="quickview"),
]

myhome/models.py
from django.db import models


# Create your models here.

class RespondPost(models.Model):
    """docstring forBlogPost."""

    name_of_responders = models.CharField(max_length=20)
    text_of_responders = models.TextField()
    name_of_office_worker = models.CharField(max_length=10)
    avatat_image_of_responder = models.FileField(upload_to='responder_avatars/')


    def __str__(self):
        return self.name_of_responders

myhome/forms.py
from django.forms import ModelForm
from .models import RespondPost


class RespondPostForm(ModelForm):

    class Meta:
        model = RespondPost
        fields = '__all__'

myhome/views.py
from django.shortcuts import render
from blog.views import blog_posts
from blog.models import BlogPost
from blog.views import blog_post_detail
from .forms import RespondPostForm
from .models import RespondPost
from django.http import HttpResponseRedirect

# Create your views here.
def responds(request):
    if request.method == 'POST':
        form_respond = RespondPostForm(request.POST, request.FILES)
        if form_respond.is_valid():
            name_of_responders = form_respond.cleaned_data['name_of_responders']
            text_of_responders = form_respond.cleaned_data['text_of_responders']
            name_of_office_worker = form_respond.cleaned_data['name_of_office_worker']
            avatat_image_of_responder = form_respond.cleaned_data['avatat_image_of_responder']
            form_respond.save()
            return HttpResponseRedirect('/')
    else:
        form_respond = RespondPostForm()
    
    context = {
        'form_respond' : form_respond,
    }

    return render(request, 'myhome/leave_respond.html', context)

def index(request):
    queryset_blog_posts = BlogPost.objects.all()
    form_respond_items = RespondPost.objects.all()

    data = {
        'queryset_blog_posts' : queryset_blog_posts,
        'form_respond_items' : form_respond_items,
        
    }
    return render(request, 'myhome/index.html', data)

def quickview(request):
    return render(request, "myhome/quickview.html", {})

myhome/templates/myhome/leave_respond.html
{% extends 'myhome/base.html' %}

{% load static %}

{% block title %}Bags{% endblock %}

{% block main %}

<div class="container">
    <form action="" method="POST" enctype="multipart/form-data" >{% csrf_token %}
        <div class="form-group">
            <label for="id_name_of_responders">Name of responders:</label>
            <input type="text" name="name_of_responders" maxlength="20" required="" id="id_name_of_responders" class="form-control">
        </div>
        <div class="form-group">
            <label for="id_text_of_responders">Text of responders:</label>
            <textarea name="text_of_responders" cols="40" rows="10" required="" id="id_text_of_responders" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label for="id_name_of_office_worker">Name of office worker:</label>
            <input type="text" name="name_of_office_worker" maxlength="10" required="" id="id_name_of_office_worker" class="form-control">
        </div>
        <div class="form-group">
            <label for="id_avatat_image_of_responder">Avatat image of responder:</label>
            <input type="file" name="avatat_image_of_responder" required="" id="id_avatat_image_of_responder" class="form-control">
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-primary">
        </div>
    </form>

</div>

{% endblock main %}