MyInternetStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('myhome.urls')),
    path('blog/', include('blog.urls')),
    path('bags/', include('bags.urls')),
    path('covid19', include('covid19.urls')),
    path('accounts/', include('allauth.urls')),
    path('contact', include('contact.urls')),
    path('children/', include('children.urls')),
    path('yobit', include('yobit.urls')),
    path('finance_ua', include('finance.urls')),
    path('men/', include('men.urls')),

    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

children/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.children, name="children"),
    path('<int:id>', views.children_view, name="children_view"),
]

men/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.men_main_view, name="men_main_view"),
    path('<int:id>', views.men_detail_view, name="men_detail_view"),

]

children/models.py
from django.db import models

# Create your models here.


class ChildrenThing(models.Model):
    """
    docstring
    """
    name_children_thing = models.CharField(max_length=30)
    new_price_children_thing = models.PositiveIntegerField()
    old_price_children_thing = models.PositiveIntegerField()
    describe_children_thing = models.TextField()
    front_image_children_thing = models.FileField(upload_to='children/title')
    back_image_children_thing = models.FileField(upload_to='children/title')
    big_detail_image_children_thing = models.FileField(upload_to='children/detail')
    middle_1_detail_image_children_thing = models.FileField(upload_to='children/detail')
    middle_2_detail_image_children_thing = models.FileField(upload_to='children/detail')
    children_published_at = models.DateTimeField()

    def __str__(self):
        return self.name_children_thing


class ChildrenThingComment(models.Model):
    children_thing = models.ForeignKey(ChildrenThing, related_name='comments', on_delete = models.CASCADE, null=True)
    name = models.CharField(max_length=80)
    phone_number = models.CharField(max_length=12)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    active = models.BooleanField(default=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete = models.CASCADE)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.children_thing)
    

children/forms.py
from django.forms import ModelForm
from .models import ChildrenThingComment


class ChildrenThingCommentForm(ModelForm):

    class Meta:
        model = ChildrenThingComment
        fields = ('name', 'email', 'phone_number', 'body' )
        

children/views.py
from django.shortcuts import render, get_object_or_404, redirect
from children.models import ChildrenThing, ChildrenThingComment
from .forms import ChildrenThingCommentForm

# Create your views here.

def children(request):
    children_things = ChildrenThing.objects.all()

    context = {
        'children_things' : children_things,
    }

    return render(request, 'children/children.html', context)


def children_view(request, id):

    children_thing = get_object_or_404(ChildrenThing, id = id)

     # List of active comments for this post
    comments = children_thing.comments.filter(active=True, parent = None) #, year, month, day, post

    if request.method == 'POST':
        # A comment was posted
        comment_form = ChildrenThingCommentForm(request.POST)
        if comment_form.is_valid():
            parent_obj = None
            # get parent comment id from hidden input
            try:
                # id integer e.g. 15
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            # if parent_id has been submitted get parent_obj id
            if parent_id:
                parent_obj = ChildrenThingComment.objects.get(id=parent_id)
                # if parent object exist
                if parent_obj:
                    # create replay comment object
                    replay_comment = comment_form.save(commit=False)
                    # assign parent_obj to replay comment
                    replay_comment.parent = parent_obj
            # create comment object but do not save to database
            new_comment = comment_form.save(commit=False)
            # assign ship to the comment
            new_comment.children_thing = children_thing
            # save
            new_comment.save()
            #return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = ChildrenThingCommentForm()

    context = {
        'children_thing' : children_thing,
        'comment_form' : comment_form,
        'comments' : comments,
    }

    return render(request, 'children/children_view.html', context)

children/templates/children/children_view.html
{% extends 'myhome/base.html' %}

{% load static %}

{% block title %} Children {% endblock %}
{% block breadcrumbs%}
<li class="item cart">
   <a href="{% url 'children' %}">Дитячі речі</a>
</li> 
<li class="item cart">
   <a href="#">{{ children_thing.name_children_thing }}</a>
</li>     
{% endblock breadcrumbs %}

{% block main %}

<main id="maincontent" class="page-main">
    <div class="container">
       <div>
          <div class="columns">
             
             <div id="main" class="site-main">
                <article class="post">
                   <div class="post-thumb light-line">
                      <a href="#"><img src="{{ children_thing.big_detail_image_children_thing.url }}" alt="{{ children_thing.name_children_thing }}"></a>
                      
                   </div>
                   <!-- .post-thumb -->
                   <div class="post-info">
                      <h3 class="post-title"><a href="#">{{ children_thing.name_children_thing }}</a></h3>
                      <ul class="post-meta">
                         <li><i class="fa fa-clock-o"></i> {{ children_thing.children_published_at }} </li>
                         <li><a href="single.html"><i class="fa fa-comments-o"></i> {{ children_thing.comments.count }} Comments</a></li>
                         <li><i class="fa fa-thumbs-o-up"></i> 256 Likes</li>
                      </ul>
                      <div class="post-desc">
                         <p>{{ children_thing.describe_children_thing }}</p>
                         <div>
                            <div class="row">
                               <div class="col-sm-6">
                                  <img src="{{ children_thing.middle_1_detail_image_children_thing.url }}" alt="">
                               </div>
                               <div class="col-sm-6">
                                  <img src="{{ children_thing.middle_2_detail_image_children_thing.url }}" alt="">
                               </div>
                            </div>
                         </div>
                         <p style="margin: 20px 0;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since. Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                      </div>
                      <!-- .post-desc -->
                   </div>
                   <!-- .post-info -->
                   <footer class="entry-footer">
                      <span class="tags-links">
                      <strong>TAGS:</strong> 
                      <a rel="tag" href="#">Wordpress</a>
                      <a rel="tag" href="#">PSD</a>
                      <a rel="tag" href="#">Design</a>
                      <a rel="tag" href="#">Men Store</a>
                      <a rel="tag" href="#">Summer</a>
                      </span>
                      <div class="single-share">
                         <strong>SHARE THIS:</strong>
                         <div class="social">
                            <ul>
                               <li><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
                               <li><a href="#" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                               <li><a href="#" target="_blank"><i class="fa fa-facebook-square"></i></a></li>
                               <li><a href="#" target="_blank"><i class="fa fa-behance"></i></a></li>
                               <li><a href="#" target="_blank"><i class="fa fa-dribbble"></i></a></li>
                            </ul>
                         </div>
                      </div>
                      <!-- .single-share -->
                      <div class="author-info">
                         <img alt="" class="avatar" src="{% static 'images/avatar/avatar.jpg' %}">
                         <div class="author-bio">
                            <h3>Administrator</h3>
                            <span class="job">Web Designer</span>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus.</p>
                         </div>
                      </div>
                   </footer>
                </article>
                <div class="comments-area" id="comments">
                   <h3 class="comments-title widget-title" style="margin-bottom: 25px;">COMMENTS ( {{ children_thing.comments.count }} )</h3>
                   <ol class="comment-list">
                       {% for comment in comments %}
                      <li class="comment">
                         <div class="comment-body">
                            <div class="comment-avatar">
                               <img class="avatar" alt="" src="{% static 'images/avatar/avatar_01.png' %}">
                            </div>
                            <!-- .comment-avatar -->
                            <header class="comment-meta">
                               <cite class="comment-author"><span><a class="url" rel="external nofollow" href="#">{{ comment.name }}</a></span></cite>
                               <div class="action-link">
                                  <a> {{ comment.created }}</a> / 
                                  <a href="#" class="comment-repost">Редагувати</a> /
                                  <a href="#" class="comment-reply-link">Видалити</a> /
                                  <a href="#" class="comment-repost">Відповісти</a> 
                               </div>
                               <!-- .action-link -->
                            </header>
                            <!-- .comment-meta -->
                            <div class="comment-content comment">
                               <p>{{ comment.body }}</p>
                            </div>
                            <!-- .comment-content -->
                         </div>
                         <!-- .comment-body -->
                         <ol class="children">
                            {% for reply in comment.replies.all %}
                            <li class="comment">
                               <div class="comment-body">
                                  <div class="comment-avatar">
                                     <img class="avatar" alt="" src="{% static 'images/avatar/avatar_02.png' %}">
                                  </div>
                                  <!-- .comment-avatar -->
                                  <header class="comment-meta">
                                     <cite class="comment-author"><span><a class="url" rel="external nofollow" href="#">{{ reply.name }}</a></span></cite>
                                     <div class="action-link">
                                        <a>{{ reply.created }}</a> / 
                                        <a href="#" class="comment-repost">Редагувати</a> /
                                        <a href="#" class="comment-reply-link">Видалити</a>
                                     </div>
                                     <!-- .action-link -->
                                  </header>
                                  <!-- .comment-meta -->
                                  <div class="comment-content comment">
                                     <p>{{ reply.body }}</p>
                                  </div>
                                  <!-- .comment-content -->
                               </div>
                               <!-- .comment-body -->
                            </li>
                            {% endfor %}
                         </ol>
                         <!-- .children -->
                         <form method="post" class="comment-form comment-form-hide">
                            {% csrf_token %}
                            <!-- Hidden input for parent comment.id -->
                            <input type="hidden" name="parent_id" value="{{ comment.id }}">
                            <div class="row">
                           <div class="col-md-4">
                             <p class="comment-form-author">
                               <!-- <label for="id_name">Ваше ім'я:</label> -->
                               <input type="text" name="name" maxlength="80" required="" id="id_name" placeholder="Ваше ім'я *">
                             </p>
                           </div>
                           <div class="col-md-4">
                             <p class="comment-form-email">
                               <!-- <label for="id_email">Email:</label> -->
                               <input type="email" name="email" maxlength="254" required="" id="id_email" placeholder="Ваш Email *">
                             </p>
                           </div>
                           <div class="col-md-4">
                             <p class="comment-form-phone">
                               <!-- <label for="id_phone_number">Номер телефону:</label> -->
                               <input type="text" name="phone_number" maxlength="12" required="" id="id_phone_number" placeholder="Ваше номер телефону *">
                             </p>
                           </div>
                         </div>
                         <p class="comment-form-comment">
                           <!-- <label for="id_body">Повідомлення:</label> -->
                           <textarea name="body" cols="40" rows="10" required="" id="id_body" aria-required="true" placeholder="Ваше повідомлення *" id="comment" style="padding: 10px; border-color: #b5b5b5; border-radius: 2px; color: #b5b5b5;"></textarea>
                         </p>
                         <p class="form-submit">
                           <input type="submit" value="Відповісти" class="btn btn-lg btn-primary" id="submit">
                        </p>
                        </form>
                      </li>
                      <!-- .comment -->
                      {% endfor %}
                   </ol>
                   <!-- .comment-list -->
                   <div class="comment-respond" id="respond">
                      <h3 class="comment-reply-title widget-title" id="reply-title">LEAVE A COMMENT</h3>
                      <form class="comment-form margin-bottom-70" id="commentform" method="post" action="#">
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-md-4">
                            <p class="comment-form-author">
                              <!-- <label for="id_name">Ваше ім'я:</label> -->
                              <input type="text" name="name" maxlength="80" required="" id="id_name" placeholder="Ваше ім'я *">
                            </p>
                          </div>
                          <div class="col-md-4">
                            <p class="comment-form-email">
                              <!-- <label for="id_email">Email:</label> -->
                              <input type="email" name="email" maxlength="254" required="" id="id_email" placeholder="Ваш Email *">
                            </p>
                          </div>
                          <div class="col-md-4">
                            <p class="comment-form-phone">
                              <!-- <label for="id_phone_number">Номер телефону:</label> -->
                              <input type="text" name="phone_number" maxlength="12" required="" id="id_phone_number" placeholder="Ваше номер телефону *">
                            </p>
                          </div>
                        </div>
                        <p class="comment-form-comment">
                          <!-- <label for="id_body">Повідомлення:</label> -->
                          <textarea name="body" cols="40" rows="10" required="" id="id_body" aria-required="true" placeholder="Ваше повідомлення *" id="comment" style="padding: 10px; border-color: #b5b5b5; border-radius: 2px; color: #b5b5b5;"></textarea>
                        </p>
                        <p class="form-submit">
                          <input type="submit" value="Залишити коментар" class="btn btn-lg btn-primary" id="submit">
                       </p>
                    </form>
                   </div>
                   <!-- #respond -->
                </div>
                <!-- .comments-area -->
             </div>
             <!-- .site-main -->
             
          </div>
       </div>
    </div>
 </main>

{% endblock main %}